set -sg escape-time 1
set -g base-index 1
setw -g pane-base-index 1

setw -g monitor-activity on
set -g visual-activity on

set -g mode-keys vi
set -g history-limit 50000

# easy-to-remember split pane commands
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# moving between panes with vim movement keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# moving between windows with vim movement keys
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# resize panes with vim movement keys
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# automatic set window title
set -g set-titles on
set -g set-titles-string "#T"

# but disallow programs to set
set -g allow-rename off

# misc
bind S set synchronize-panes
bind P command-prompt -p 'save history to filename:' -I '~/tmux.history' 'capture-pane -e -S -32768 ; save-buffer %1 ; delete-buffer'

# suggested by Neovim :checkhealth
set-option -g focus-events on
set-option -ga terminal-overrides ',alacritty:Tc'
set-option -g default-terminal "tmux-256color"

# https://github.com/joshmedeski/sesh
bind-key "T" run-shell "sesh connect \"$(
  sesh list -t --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi \
    --header '^a all ^t tmux ^g repos ^x zoxide ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:reload(sesh list --icons)' \
    --bind 'ctrl-t:reload(sesh list -t --icons)' \
    --bind 'ctrl-g:reload(fd -H -d 6 -g .git ~/git -X dirname)' \
    --bind 'ctrl-x:reload(sesh list -z --icons)' \
    --bind 'ctrl-f:reload(fd -H -d 2 -t d . ~)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

# https://github.com/folke/tokyonight.nvim/blob/main/extras/tmux/tokyonight_night.tmux
# TokyoNight colors for Tmux

set -g mode-style "fg=#7aa2f7,bg=#3b4261"

set -g message-style "fg=#7aa2f7,bg=#3b4261"
set -g message-command-style "fg=#7aa2f7,bg=#3b4261"

set -g pane-border-style "fg=#3b4261"
set -g pane-active-border-style "fg=#7aa2f7"

set -g status "on"
set -g status-justify "left"

set -g status-style "fg=#7aa2f7,bg=#16161e"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=#15161e,bg=#7aa2f7] #S #[fg=#7aa2f7,bg=#16161e]"
set -g status-right "#[fg=#7aa2f7,bg=#3b4261] %Y-%m-%d %H:%M #[fg=#15161e,bg=#7aa2f7] #h "

setw -g window-status-activity-style "underscore,fg=#a9b1d6,bg=#16161e"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#a9b1d6,bg=#16161e"
setw -g window-status-format "#[fg=#565f89,bg=#16161e] #I #W "
setw -g window-status-current-format "#[fg=#7aa2f7,bg=#3b4261] #I #W "

# Required for sixel
set -g allow-passthrough on

# update environ
set-option -g update-environment "TERM TERM_PROGRAM DISPLAY WAYLAND_DISPLAY SWAYSOCK SSH_AUTH_SOCK"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @resurrect-capture-pane-contents 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.local/tpm/tpm'
