line-length = 120

[lint]
# https://docs.astral.sh/ruff/rules/
select = ['F', 'E', 'W', 'UP',]
ignore = [
  'E265', # no-space-after-block-comment
  'E501', # line-too-long

  # This rule does not recognize type hints.
  # Pyright does the same job, but better.
  # https://github.com/astral-sh/ruff/issues/15482
  'F821', # undefined-name
]

[lint.isort]
length-sort = true
force-single-line = true

[format]
quote-style = 'single'
